import os

from playwright.sync_api import sync_playwright


with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page(viewport={"width": 1280, "height": 900})
    page.goto(os.getenv("STUDY_AGENT_UI_URL", "http://127.0.0.1:5173"))
    page.wait_for_load_state("networkidle")
    page.screenshot(path="study-agent-home.png", full_page=True)
    assert page.get_by_text("StudyAgent").first.is_visible()
    assert page.get_by_text("AI 快捷入口").is_visible()
    page.get_by_role("button", name="知识库", exact=True).click()
    page.wait_for_timeout(300)
    page.get_by_role("button", name="新建").click()
    page.get_by_placeholder("例如：计算机网络").fill("浏览器测试库")
    page.get_by_role("button", name="创建知识库").click()
    page.wait_for_timeout(400)
    assert page.get_by_text("浏览器测试库").first.is_visible()
    page.get_by_role("button", name="向 AI 提问").click()
    page.wait_for_timeout(300)
    print(page.locator("body").inner_text()[-800:])
    assert page.get_by_text("AI 学习助手").is_visible()
    page.get_by_placeholder("问一个关于资料的问题…").fill("资料里有什么？")
    page.locator("form.chat-input button").click()
    page.wait_for_timeout(500)
    assert page.get_by_text("当前知识库资料不足以回答这个问题。").is_visible()
    page.locator(".chat-head button").click()
    page.get_by_role("button", name="学习", exact=True).click()
    page.wait_for_timeout(300)
    page.get_by_role("button", name="新计划").click()
    page.get_by_role("button", name="生成草案").click()
    page.wait_for_timeout(400)
    assert page.get_by_text("待确认").is_visible()
    page.get_by_role("button", name="确认并开始").click()
    page.wait_for_timeout(400)
    assert page.get_by_text("今日任务").is_visible()
    browser.close()
